version: '3'
services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      
  frontend:
    build: ./Frontend/PocketTrainer
    ports:
      - "4200:80"
    restart: unless-stopped

  backend:
    build: ./Backend    
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: unless-stopped
